### ISSUE TITLE
Better biblogram production deployment

### ISSUE THREAD

**Issue by stranger-danger-zamu** [PussTheCat-org/PussTheCat.org-Wiki#1]
https://github.com/PussTheCat-org/PussTheCat.org-Wiki/blob/68f93ba13db27b8ab6ce7f3054df29c021c9550e/bibliogram-janky-setup.md#L30

Ended up perusing your wiki via [this reddit thread](https://reddit.com/r/selfhosted/comments/sebmxi/g_suite_alternative/). Unfortunately I don't see how you'd make a good docker container for bibliogram due to the runaway child process problem, if you still want something better though...

---

Assuming you are running some normal distribution that has systemd, you can actually configure this pretty simply.

```ini
# /etc/systemd/system/bibliogram.service
[Unit]
Description=bibliogram service

[Service]
Type=simple
Restart=always # restarts whenever the service stops even when successfully exiting (ie. updating)
RuntimeMaxSec=6h # this sets a max uptime of 6 hours
WorkingDirectory=/path/to/bibliogram-updater/ # set PWD to ensure that the env vars are correctly read
ExecStart=/path/to/bibliogram-updater/run.fish # change the path to the correct one.

#security stuff
NoNewPrivileges=yes
RestrictSUIDSGID=yes
DynamicUser=yes
PrivateTmp=yes
RemoveIPC=yes
BindPaths=/path/to/bibliogram-updater/
```

Simply create the required config and install it via the script then just `sudo systemctl enable --now bibliogram.service` and you have a working service. Additionally, it should auto update at some point due to the 6h restart window.

With this you get away from running things in a random screen (which can fail and not restart if the system reboots), it automatically restarts after 6 hours, and _logs successes, failures, and restarts_.

**Comment by TheFrenchGhosty** [comment]
@stranger-danger-zamu 

Hello there!

Sorry I didn't see this issue before.

The Bibliogram setup is now "solved", since I made (earlier this week) a proper docker container for Bibliogram): https://github.com/PussTheCat-org/docker-bibliogram-quay

This is otherwise indeed something that should work (I really haven't dug enough into systemd)
